name: Howse CC
title: Howse CC | Security Engineer
description: 
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  # - title: About
  #   url: /about
  # - title: Posts
  #   url: /posts
  - title: Contact
    url: /contact
email: jake@howse.cc
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mqkvolzr
